### ISSUE TITLE
Seems interesting！

### ISSUE THREAD

**Issue by qianxliu** [ElpsyCN/elpsycn.github.io#1]
组织好像很有意思的样子！我能加入吗？

本人是做Android和Unity游戏开发的，对未来道具也很感兴趣！

不知道怎么联系，就open an issue了，不常用QQ

**Comment by qianxliu** [comment]
那个，其实我是在找游戏开发相关的组织，可是找不到，没有人喜欢做这些无聊的事，最后看到这个组织
第一个组织人员水平和勤奋度都过低了
第二个组织成员已经没有维护的心思了，有点难以接受，对我这种刚打算加入的人不是很友好，当时当做是一个知名商业游戏引擎开发团队了
如果再找不到组织我应该就自己开发了，证明和我有同样想法而且让我注意到的确实不多，但是也没有办法

而且作者太正式了，你所说的工程也不能说是协作，都是一人做罢了，所以开设其他别类项目又有什么关系呢?作者一定几乎都没用过checkout 或者pull吧，通过代码可以看出作者不算很水的前端
虽然最后可能是独立游戏，但是有着想与人合作的心情

**Comment by qianxliu** [comment]
也想做一些东西，steins;gate我是看过的
作者是中国传媒大学的吗？

话说作者是如何加入这种组织的：https://github.com/NVIDIAGameWorks
虽然似乎也有fork来的工程

还有，GitHub组织有一个Pin 重要工程的功能，似乎未来道具研究所一直没有用
Location设置China确实设置对了，为了方便我就是通过这个检索字检索到的

**Comment by qianxliu** [comment]
我是想做一个Action-RPG和一些剧情，希望这次再也不鸽了，而且已经有Demo成果了
剧情方面希望共笔，怕我又鸽了或者没有心思坚持下去了
也算是未来道具吧
也可能搬运一些数学物理算法相关的，没准能有什么突破
游戏和剧情是艺术上的未来道具，数学物理算法是技术上的未来道具
如果有网页的话，可以做成Android端的

还有也应该研究一下Discord机器人，国外常用这个网页端聊天工具，就是国内延迟大约100ms

**Comment by YunYouJun** [comment]
> 那个，其实我是在找游戏开发相关的组织，可是找不到，没有人喜欢做这些无聊的事，最后看到这个组织
第一个组织人员水平和勤奋度都过低了
第二个组织成员已经没有维护的心思了，有点难以接受，对我这种刚打算加入的人不是很友好，当时当做是一个知名商业游戏引擎开发团队了

首先，为何游戏会是无聊的事呢？如果自己认为无聊，就大事不妙了。

后面几句的语义没有理清楚，这个第一个组织和第二个组织分别指的是？
是指您之前曾经加入过的两个组织，还是指当前的 ElpsyCN，还是其他意思？

> 而且作者太正式了，你所说的工程也不能说是协作，都是一人做罢了，所以开设其他别类项目又有什么关系呢?作者一定几乎都没用过checkout 或者pull吧，通过代码可以看出作者不算很水的前端

在初次接触时，正式一点的用语更有利于双方快速明白对方所表达的意思。自认为应当没有矫枉过正。
只不过挂在 GitHub 上的公有项目多为个人项目，断言 `一定几乎都没用过 checkout 或者 pull` 是不是不大合适？

`可以看出作者不算很水的前端` （也就是比较水的前端），想必是从个人项目中得出，但您的公开 Repo 似乎较少，很难进一步了解您的情况。

> 作者是中国传媒大学的吗？

是，但这似乎并不重要。

> 话说作者是如何加入这种组织的：https://github.com/NVIDIAGameWorks

详见开发者中心，

> 我是想做一个Action-RPG和一些剧情，希望这次再也不鸽了，而且已经有Demo成果了
剧情方面希望共笔，怕我又鸽了或者没有心思坚持下去了

Demo 效果是否有可展示视频？
剧情本身需要一定的文字功底，互相的水平还不了解，可能有些为时过早，合作阻力也会较大。

以及当前组织主要是以开源项目为主，更像是为爱发电。对 Android 方面也没有任何研究，无法提供任何助力。
那么本质和自己一个人没有什么区别，何不选择更有成就感的方式呢？

> 还有也应该研究一下Discord机器人，国外常用这个网页端聊天工具，就是国内延迟大约100ms

当前的 el-bot （QQ 机器人）则是基于 mirai 旨在作为个人助手解决 CoolQ 发送图片收费、跨平台笨重，个人使用过于繁琐等问题。（因为尚无同类型开源项目，所以开坑。）

Discord 机器人的相关开源项目应该已有很多，且其本身也有机器人机制，也许并不需要做重复工作。

**Comment by qianxliu** [comment]
> 回复
- 作者这是一些人的commit代码修改量，我觉得每个人都有自己不了解的地方吧……
<a href="https://github.com/ADD-SP/MCOS/commit/0b33a91ce60be819f7050e83b184bd8783e10244">ADD-SP代码块链接</a> 
<a href="https://github.com/Neteraxe/HiddenTale/commit/bfa8a54e6fc7bc71c0ed1ee2d74b48947b1c83ff">neteraxe代码块链接</a>
作者我就且冒犯传一下您的commit链接
https://github.com/ElpsyCN/el-bot-js/commit/f889d452122e23543eafde3b8d2e00569b6fe0fb
第一个和第二个都不是初始化工程，是后续的修改。
我的工程不怎么愿意让人注意到，因为是为别人做的，但是开源，有人搜到了算他好运
- 这是游戏Demo
![image](https://user-images.githubusercontent.com/53852392/86589044-7755ec80-bfbf-11ea-97d6-78f55e08f422.png)
- 之前接触过两个组织，似乎都没什么太大加入的意义，有些人有理想却懒惰，有些人有理想有能力但是似乎都是一人在做工作，程序说到底不是炫技……
- 还有这些似乎都不是关键点……我是对你的组织比较感兴趣，我并不在乎有无方法提供助力，只是希望和志同道合的开发者做一些有趣的事情，而我愿意负责Android和游戏方面的研究开发，第二个组织实际上不需要我，因为有大佬坐镇(笑)
- 我是对您的组织比较感兴趣，如果不愿意让我加入的话close这个issue就可以，`我并不很愿意给并不志同道合的的人提供我做的游戏信息`，而且作者似乎不需要Android和游戏开发相关的人员加入，这些事情或者作者没有考虑过，或者能很轻易的Handle，因为作者不是一般的前端，是GitHub开源的大前端

### 题外话，算是一些废话
- PS:这是第二个组织所研究的事物 https://github.com/UnknownDomainGame/PanguEngine <br>
我接触过开发者，很谦虚，一直说我是大佬(笑)

### 附录：请大佬当我什么都没有说过，我没有任何妄加揣测大佬技术的意思，如果大佬感觉不合适了，我感到非常抱歉，前端就是可以写几万行代码实现炫酷功能，这是技术的体现，吾辈望尘莫及

### @YunYouJun 请您回复我，或者close这个issue吧，open着怪奇怪的，看得出作者似乎不常用GitHub的邮件通知提醒功能

**Comment by Neteraxe** [comment]
作者，我承认您水平很高，所以，请关闭这个issue，当我什么都没有说过

**Comment by YunYouJun** [comment]
> @YunYouJun 请您回复我，或者close这个issue吧，open着怪奇怪的，看得出作者似乎不常用GitHub的邮件通知提醒功能

看得出，您似乎不知道自己也可以 Close Issue。

首先没有回复，是因为我今日上午考试，而昨日需要复习准备。其次，我和 @ADD-SP 一直在揣摩您贴 commit 链接的用意，实在没有明白所指含义。

其次斗胆给您一点建议，善用 `.gitignore`，来忽略仓库里的一些无用缓存文件，这有利于维持较小的体积和保持仓库整洁。
commit 时，提供一些描述信息，也更有利于对应工作的识别和后续的维护。

![image](https://user-images.githubusercontent.com/25154432/86714800-2511db80-c052-11ea-9f6f-2471078e6f68.png)

```txt
# Gradle cache directory
.gradle/
```

> 前端就是可以写几万行代码实现炫酷功能，这是技术的体现

几万行代码又是所指何意，为何会是技术的体现？

**Comment by qianxliu** [comment]
@ADD-SP 我没有任何用意。如果作者确实足够厉害，我希望作者不要坐井观天，这个issue我就先放在这里。不吹不黑，作者您是我近期见过的最厉害的大佬。艾特您好友的目的是因为您希望@您的好友。<br>
还有，作者确实是大佬，不吹不黑。
